version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    pid: "host"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
