services:
  rpstest:
    image: rpstest
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: RpsTest/Dockerfile

    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
